name: TodoApp
options:
  bundleIdPrefix: com.demo
  deploymentTarget:
    iOS: "17.0"

settings:
  SWIFT_VERSION: "5.9"

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.15.0
  SwiftNavigation:
    url: https://github.com/pointfreeco/swift-navigation
    from: 2.2.0
  Factory:
    url: https://github.com/hmlongco/Factory
    from: 2.3.0

targets:
  TodoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources/TodoApp
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Factory
        product: Factory
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.demo.TodoApp
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES

  TodoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/TodoAppTests
    dependencies:
      - target: TodoApp
      - package: ComposableArchitecture
        product: ComposableArchitecture
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.demo.TodoAppTests
      GENERATE_INFOPLIST_FILE: YES
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
